const withOrder = (columns) => columns.map((column, index) => ({
  minWidth: column.minWidth || 125,
  visible: column.visible !== false,
  ...column,
  order: column.order || index + 1,
}));

export const SALES_QUOTATION_WORKBOOK_COLUMNS = withOrder([
  { key: 'itemNo', label: 'Item No.', minWidth: 160 },
  { key: 'itemDescription', label: 'Item Description', minWidth: 240 },
  { key: 'quantity', label: 'Quantity', minWidth: 95, numeric: true },
  { key: 'uomName', label: 'UoM Name', minWidth: 120, readOnly: true },
  { key: 'hsnCode', label: 'HSN', minWidth: 105 },
  { key: 'unitPrice', label: 'Unit Price', minWidth: 110, numeric: true },
  { key: 'taxCode', label: 'Tax Code', minWidth: 115 },
  { key: 'totalLC', label: 'Total (LC)', minWidth: 115, readOnly: true, numeric: true },
  { key: 'U_PackingType', label: 'Packing-Type', minWidth: 135, isUdf: true },
  { key: 'taxCodeRepeat', label: 'TaxCode', minWidth: 110, valueKey: 'taxCode', rendererKey: 'taxCode' },
  { key: 'price', label: 'Price', minWidth: 95, numeric: true },
  { key: 'sellerBrokerage', label: 'Seller Brokerage', minWidth: 135 },
  { key: 'buyerBrokerage', label: 'Buyer Brokerage', minWidth: 130 },
  { key: 'buyerDelivery', label: 'Buyer - Delivery', minWidth: 135 },
  { key: 'sellerDelivery', label: 'Seller - Delivery', minWidth: 135 },
  { key: 'buyerPaymentTerms', label: 'Buyer - Terms of payment', minWidth: 180 },
  { key: 'sellerPaymentTerms', label: 'Seller - Terms of Payment', minWidth: 180 },
  { key: 'buyerQuality', label: 'Buyer - Quality', minWidth: 135 },
  { key: 'sellerQuality', label: 'Seller - Quality', minWidth: 135 },
  { key: 'buyerPrice', label: 'Buyer - Price', minWidth: 120 },
  { key: 'sellerPrice', label: 'Seller - Price', minWidth: 120 },
  { key: 'buyerSpecialInstruction', label: 'Buyer - Special Instruction', minWidth: 190 },
  { key: 'sellerSpecialInstruction', label: 'Seller - Special Instruction', minWidth: 190 },
  { key: 'sellerBrokerageAmtPer', label: 'Seller Brokerage(Amt./Per)', minWidth: 175 },
  { key: 'sellerBrokeragePercent', label: 'Seller Brokerage in Percentage', minWidth: 190, numeric: true },
  { key: 'stcode', label: 'STCODE', minWidth: 110 },
  { key: 'sellerItem', label: 'S_Item', minWidth: 115 },
  { key: 'sellerQty', label: 'S_Qty', minWidth: 95, numeric: true },
  { key: 'specialRebate', label: 'Special Rebate', minWidth: 120 },
  { key: 'commission', label: 'Commision', minWidth: 110 },
  { key: 'sellerBrokeragePerQty', label: 'BrokPerQty', minWidth: 110 },
  { key: 'U_Fix_Brock_B', label: 'FIX Brok BUYER', minWidth: 135, isUdf: true, numeric: true },
  { key: 'U_Fix_Brock_S', label: 'Fix Brock Seller', minWidth: 140, isUdf: true, numeric: true },
]);

export const DELIVERY_WORKBOOK_COLUMNS = withOrder([
  { key: 'itemNo', label: 'Item No.', minWidth: 160 },
  { key: 'itemDescription', label: 'Item Description', minWidth: 240 },
  { key: 'quantity', label: 'Quantity', minWidth: 85, numeric: true },
  { key: 'uomName', label: 'UoM Name', minWidth: 120, readOnly: true },
  { key: 'hsnCode', label: 'HSN', minWidth: 95 },
  { key: 'unitPrice', label: 'Unit Price', minWidth: 110, numeric: true },
  { key: 'taxCode', label: 'Tax Code', minWidth: 110 },
  { key: 'U_PackingType', label: 'Packing-Type', minWidth: 140, isUdf: true },
  { key: 'U_GrossWt', label: 'GrossWt', minWidth: 110, isUdf: true, numeric: true },
  { key: 'U_TotalPackage', label: 'Total-Package', minWidth: 130, isUdf: true, numeric: true },
  { key: 'totalLC', label: 'Total (LC)', minWidth: 115, readOnly: true, numeric: true },
  { key: 'whse', label: 'Whse', minWidth: 75 },
  { key: 'binLocationAllocation', label: 'Bin Location Allocation', minWidth: 160 },
  { key: 'priceAfterDiscount', label: 'Price after Discount', minWidth: 130, readOnly: true },
  { key: 'itemCost', label: 'Item Cost', minWidth: 110 },
  { key: 'taxCodeRepeat', label: 'TaxCode', minWidth: 110, valueKey: 'taxCode', rendererKey: 'taxCode' },
  { key: 'price', label: 'Price', minWidth: 95, numeric: true },
  { key: 'sellerBrokerage', label: 'Seller Brokerage', minWidth: 120 },
  { key: 'buyerBrokerage', label: 'Buyer Brokerage', minWidth: 120 },
  { key: 'buyerDelivery', label: 'Buyer - Delivery', minWidth: 120 },
  { key: 'sellerDelivery', label: 'Seller - Delivery', minWidth: 120 },
  { key: 'buyerPaymentTerms', label: 'Buyer - Terms of payment', minWidth: 170 },
  { key: 'sellerPaymentTerms', label: 'Seller - Terms of Payment', minWidth: 170 },
  { key: 'buyerQuality', label: 'Buyer - Quality', minWidth: 170 },
  { key: 'sellerQuality', label: 'Seller - Quality', minWidth: 170 },
  { key: 'buyerPrice', label: 'Buyer - Price', minWidth: 110 },
  { key: 'sellerPrice', label: 'Seller - Price', minWidth: 110 },
  { key: 'buyerSpecialInstruction', label: 'Buyer - Special Instruction', minWidth: 180 },
  { key: 'sellerSpecialInstruction', label: 'Seller - Special Instruction', minWidth: 180 },
  { key: 'sellerBrokerageAmtPer', label: 'Seller Brokerage(Amt./Per)', minWidth: 155 },
  { key: 'sellerBrokeragePercent', label: 'Seller Brokerage in Percentage', minWidth: 170, numeric: true },
  { key: 'stcode', label: 'STCODE', minWidth: 110 },
  { key: 'sellerItem', label: 'S_Item', minWidth: 110 },
  { key: 'sellerQty', label: 'S_Qty', minWidth: 90, numeric: true },
  { key: 'specialRebate', label: 'Special Rebate', minWidth: 110 },
  { key: 'commission', label: 'Commision', minWidth: 100 },
  { key: 'sellerBrokeragePerQty', label: 'BrokPerQty', minWidth: 100 },
  { key: 'U_Fix_Brock_B', label: 'FIX Brok BUYER', minWidth: 135, isUdf: true, numeric: true },
  { key: 'U_Fix_Brock_S', label: 'Fix Brock Seller', minWidth: 140, isUdf: true, numeric: true },
  { key: 'batch', label: 'Batch', minWidth: 95 },
]);

export const AR_INVOICE_WORKBOOK_COLUMNS = withOrder([
  { key: 'itemNo', label: 'Item No.', minWidth: 160 },
  { key: 'itemDescription', label: 'Item Description', minWidth: 240 },
  { key: 'quantity', label: 'Quantity', minWidth: 90, numeric: true },
  { key: 'unitPrice', label: 'Unit Price', minWidth: 105, numeric: true },
  { key: 'stdDiscount', label: 'Discount %', minWidth: 95, numeric: true },
  { key: 'taxCode', label: 'Tax Code', minWidth: 120 },
  { key: 'wTaxLiable', label: 'WTax Liable', minWidth: 100, type: 'yesNo' },
  { key: 'totalLC', label: 'Total (LC)', minWidth: 110, numeric: true },
  { key: 'whse', label: 'Whse', minWidth: 90 },
  { key: 'binLocationAllocation', label: 'Bin Location Allocation', minWidth: 160 },
  { key: 'commPercent', label: 'Comm. %', minWidth: 95, numeric: true },
  { key: 'glAccount', label: 'G/L Account', minWidth: 135 },
  { key: 'distRule', label: 'Distr. Rule', minWidth: 105 },
  { key: 'uomCode', label: 'UoM Code', minWidth: 105 },
  { key: 'uomName', label: 'UoM Name', minWidth: 120, readOnly: true },
  { key: 'cogsDistRule', label: 'COGS Distr. Rule', minWidth: 135 },
  { key: 'countryOfOrigin', label: 'Country/Region of Origin', minWidth: 185 },
  { key: 'assessableValue', label: 'Assessable Value (INR)', minWidth: 150 },
  { key: 'loc', label: 'Loc.', minWidth: 115, readOnly: true },
  { key: 'blanketAgreementNo', label: 'Blanket Agreement No.', minWidth: 170 },
  { key: 'hsnCode', label: 'HSN', minWidth: 115 },
  { key: 'sacCode', label: 'SAC', minWidth: 95 },
  { key: 'U_Cost_Sheet', label: 'Cost-Sheet', minWidth: 125, isUdf: true },
  { key: 'U_PackingType', label: 'Packing-Type', minWidth: 135, isUdf: true },
  { key: 'U_ContainerType', label: 'Container Type', minWidth: 135, isUdf: true },
  { key: 'U_GrossWt', label: 'GrossWt', minWidth: 110, isUdf: true, numeric: true },
  { key: 'U_TotalPackage', label: 'Total-Package', minWidth: 130, isUdf: true, numeric: true },
  { key: 'taxCodeRepeat', label: 'TaxCode', minWidth: 110, valueKey: 'taxCode', rendererKey: 'taxCode' },
  { key: 'price', label: 'Price', minWidth: 95, numeric: true },
  { key: 'sellerBrokerage', label: 'Seller Brokerage', minWidth: 135 },
  { key: 'buyerBrokerage', label: 'Buyer Brokerage', minWidth: 130 },
  { key: 'buyerDelivery', label: 'Buyer - Delivery', minWidth: 135 },
  { key: 'sellerDelivery', label: 'Seller - Delivery', minWidth: 135 },
  { key: 'buyerPaymentTerms', label: 'Buyer - Terms of payment', minWidth: 180 },
  { key: 'sellerPaymentTerms', label: 'Seller - Terms of Payment', minWidth: 180 },
  { key: 'buyerQuality', label: 'Buyer - Quality', minWidth: 135 },
  { key: 'sellerQuality', label: 'Seller - Quality', minWidth: 135 },
  { key: 'buyerPrice', label: 'Buyer - Price', minWidth: 120 },
  { key: 'sellerPrice', label: 'Seller - Price', minWidth: 120 },
  { key: 'buyerSpecialInstruction', label: 'Buyer - Special Instruction', minWidth: 190 },
  { key: 'sellerSpecialInstruction', label: 'Seller - Special Instruction', minWidth: 190 },
  { key: 'sellerBrokerageAmtPer', label: 'Seller Brokerage(Amt./Per)', minWidth: 175 },
  { key: 'sellerBrokeragePercent', label: 'Seller Brokerage in Percentage', minWidth: 190, numeric: true },
  { key: 'stcode', label: 'STCODE', minWidth: 110 },
  { key: 'sellerItem', label: 'S_Item', minWidth: 115 },
  { key: 'sellerQty', label: 'S_Qty', minWidth: 95, numeric: true },
  { key: 'specialRebate', label: 'Special Rebate', minWidth: 120 },
  { key: 'commission', label: 'Commision', minWidth: 110 },
  { key: 'sellerBrokeragePerQty', label: 'BrokPerQty', minWidth: 110 },
  { key: 'U_Fix_Brock_B', label: 'FIX Brok BUYER', minWidth: 135, isUdf: true, numeric: true },
  { key: 'U_Fix_Brock_S', label: 'Fix Brock Seller', minWidth: 140, isUdf: true, numeric: true },
]);

export const AR_CREDIT_MEMO_WORKBOOK_COLUMNS = withOrder([
  { key: 'itemNo', label: 'Item No.', minWidth: 160 },
  { key: 'itemDescription', label: 'Item Description', minWidth: 220 },
  { key: 'quantity', label: 'Quantity', minWidth: 90, numeric: true },
  { key: 'unitPrice', label: 'Unit Price', minWidth: 95, numeric: true },
  { key: 'stdDiscount', label: 'Discount %', minWidth: 95, numeric: true },
  { key: 'taxCode', label: 'Tax Code', minWidth: 115 },
  { key: 'wTaxLiable', label: 'WTax Liable', minWidth: 100, type: 'yesNo' },
  { key: 'totalLC', label: 'Total (LC)', minWidth: 110, readOnly: true, numeric: true },
  { key: 'whse', label: 'Whse', minWidth: 90 },
  { key: 'binLocationAllocation', label: 'Bin Location Allocation', minWidth: 160 },
  { key: 'uomCode', label: 'UoM Code', minWidth: 105 },
  { key: 'itemCost', label: 'Item Cost', minWidth: 110 },
  { key: 'countryOfOrigin', label: 'Country/Region of Origin', minWidth: 185 },
  { key: 'distRule', label: 'Distr. Rule', minWidth: 105 },
  { key: 'cogsDistRule', label: 'COGS Distr. Rule', minWidth: 135 },
  { key: 'loc', label: 'Loc.', minWidth: 115, readOnly: true },
  { key: 'withoutQtyPosting', label: 'Without Qty Posting', minWidth: 145, type: 'yesNo' },
  { key: 'enableSettingCost', label: 'Enable Setting Cost', minWidth: 140, type: 'checkbox' },
  { key: 'returnCost', label: 'Return Cost (LC)', minWidth: 125, numeric: true },
  { key: 'blanketAgreementNo', label: 'Blanket Agreement No.', minWidth: 170 },
  { key: 'hsnCode', label: 'HSN', minWidth: 115 },
  { key: 'sacCode', label: 'SAC', minWidth: 95 },
  { key: 'U_Cost_Sheet', label: 'Cost-Sheet', minWidth: 125, isUdf: true },
  { key: 'U_PackingType', label: 'Packing-Type', minWidth: 135, isUdf: true },
  { key: 'U_ContainerType', label: 'Container Type', minWidth: 135, isUdf: true },
  { key: 'U_GrossWt', label: 'GrossWt', minWidth: 110, isUdf: true, numeric: true },
  { key: 'U_TotalPackage', label: 'Total-Package', minWidth: 130, isUdf: true, numeric: true },
  { key: 'taxCodeRepeat', label: 'TaxCode', minWidth: 110, valueKey: 'taxCode', rendererKey: 'taxCode' },
  { key: 'price', label: 'Price', minWidth: 95, numeric: true },
  { key: 'sellerBrokerage', label: 'Seller Brokerage', minWidth: 135 },
  { key: 'buyerBrokerage', label: 'Buyer Brokerage', minWidth: 130 },
  { key: 'buyerDelivery', label: 'Buyer - Delivery', minWidth: 135 },
  { key: 'sellerDelivery', label: 'Seller - Delivery', minWidth: 135 },
  { key: 'buyerPaymentTerms', label: 'Buyer - Terms of payment', minWidth: 180 },
  { key: 'sellerPaymentTerms', label: 'Seller - Terms of Payment', minWidth: 180 },
  { key: 'buyerQuality', label: 'Buyer - Quality', minWidth: 135 },
  { key: 'sellerQuality', label: 'Seller - Quality', minWidth: 135 },
  { key: 'buyerPrice', label: 'Buyer - Price', minWidth: 120 },
  { key: 'sellerPrice', label: 'Seller - Price', minWidth: 120 },
  { key: 'buyerSpecialInstruction', label: 'Buyer - Special Instruction', minWidth: 190 },
  { key: 'sellerSpecialInstruction', label: 'Seller - Special Instruction', minWidth: 190 },
  { key: 'sellerBrokerageAmtPer', label: 'Seller Brokerage(Amt./Per)', minWidth: 175 },
  { key: 'sellerBrokeragePercent', label: 'Seller Brokerage in Percentage', minWidth: 190, numeric: true },
  { key: 'stcode', label: 'STCODE', minWidth: 110 },
  { key: 'sellerItem', label: 'S_Item', minWidth: 115 },
  { key: 'sellerQty', label: 'S_Qty', minWidth: 95, numeric: true },
  { key: 'specialRebate', label: 'Special Rebate', minWidth: 120 },
  { key: 'commission', label: 'Commision', minWidth: 110 },
  { key: 'sellerBrokeragePerQty', label: 'BrokPerQty', minWidth: 110 },
  { key: 'U_Fix_Brock_B', label: 'FIX Brok BUYER', minWidth: 135, isUdf: true, numeric: true },
  { key: 'U_Fix_Brock_S', label: 'Fix Brock Seller', minWidth: 140, isUdf: true, numeric: true },
]);
